/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaansmk;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import javax.servlet.ServletOutputStream;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperReport;


/**
 *
 * @author Atthoriq
 */
public class petugas_menu extends javax.swing.JFrame {
    ResultSet rs = null;
    Connection CC = null;
    PreparedStatement pst = null;
    /**
     * Creates new form petugas_menu
     */
    public petugas_menu() {
        initComponents();
        CC = new koneksi().connect();
        userLogin();
        hakakses();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void userLogin(){
    status.setText(UserSession.getUserLogin());
    }
    
    private void hakakses() {
    String user=status.getText();
        if(user.equals("Admin") || user.equals("admin")){
       //Master
        DataBuku.setEnabled(true);
        DataPeminjam.setEnabled(true);
        DataAnggota.setEnabled(true);
        DataDenda.setEnabled(true);
        DataBukuHilang.setEnabled(true);
      //transaksi
        LBukuHilang.setEnabled(true);
        panelAdmin.setEnabled(true);
      //Laporan
        LaporanPeminjaman.setEnabled(true);
        LaporanAnggota.setEnabled(true);
        LaporanBukuMasuk.setEnabled(true);
        LaporanBukuHilang.setEnabled(true);
        LaporanPengembalian.setEnabled(true);
      //status
        Logout.setEnabled(true);
        }
        else {
        
          //Master
        DataBuku.setEnabled(true);
        DataPeminjam.setEnabled(true);
        DataAnggota.setEnabled(true);
        DataDenda.setEnabled(true);
        DataBukuHilang.setEnabled(true);
      //transaksi
        LBukuHilang.setEnabled(true);
        panelAdmin.setEnabled(false);
      //Laporan
        LaporanPeminjaman.setEnabled(true);
        LaporanAnggota.setEnabled(true);
        LaporanBukuMasuk.setEnabled(true);
        LaporanBukuHilang.setEnabled(true);
        LaporanPengembalian.setEnabled(true);
      //status
        Logout.setEnabled(true);
        }
        }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        DataBuku = new javax.swing.JMenuItem();
        DataPeminjam = new javax.swing.JMenuItem();
        DataAnggota = new javax.swing.JMenuItem();
        DataDenda = new javax.swing.JMenuItem();
        DataBukuHilang = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        LBukuHilang = new javax.swing.JRadioButtonMenuItem();
        panelAdmin = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LaporanPeminjaman = new javax.swing.JMenuItem();
        LaporanAnggota = new javax.swing.JMenuItem();
        LaporanBukuMasuk = new javax.swing.JMenuItem();
        LaporanBukuHilang = new javax.swing.JMenuItem();
        LaporanPengembalian = new javax.swing.JMenuItem();
        status = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBackground(new java.awt.Color(199, 234, 238));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Konfirmasi Peminjaman");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Konfirmasi Pengembalian");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Konfirmasi Pendaftaran Anggota");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ret.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pinja.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/kartuanggota.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Wallet-22-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Konfirmasi Bayar Denda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(199, 234, 238));

        jMenu2.setText("Master");

        DataBuku.setText("Data Buku");
        DataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBukuActionPerformed(evt);
            }
        });
        jMenu2.add(DataBuku);

        DataPeminjam.setText("Data Peminjam");
        DataPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPeminjamActionPerformed(evt);
            }
        });
        jMenu2.add(DataPeminjam);

        DataAnggota.setText("Data Anggota");
        DataAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataAnggotaActionPerformed(evt);
            }
        });
        jMenu2.add(DataAnggota);

        DataDenda.setText("Data Denda");
        DataDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataDendaActionPerformed(evt);
            }
        });
        jMenu2.add(DataDenda);

        DataBukuHilang.setText("Data Buku Hilang");
        DataBukuHilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBukuHilangActionPerformed(evt);
            }
        });
        jMenu2.add(DataBukuHilang);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Transaksi");

        LBukuHilang.setSelected(true);
        LBukuHilang.setText("Laporan Buku Hilang");
        LBukuHilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBukuHilangActionPerformed(evt);
            }
        });
        jMenu4.add(LBukuHilang);

        panelAdmin.setSelected(true);
        panelAdmin.setText("Panel Admin");
        panelAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelAdminActionPerformed(evt);
            }
        });
        jMenu4.add(panelAdmin);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Report");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        LaporanPeminjaman.setText("Laporan Peminjaman");
        LaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPeminjamanActionPerformed(evt);
            }
        });
        jMenu3.add(LaporanPeminjaman);

        LaporanAnggota.setText("Laporan Anggota Baru");
        LaporanAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanAnggotaActionPerformed(evt);
            }
        });
        jMenu3.add(LaporanAnggota);

        LaporanBukuMasuk.setText("Laporan Buku Masuk");
        LaporanBukuMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanBukuMasukActionPerformed(evt);
            }
        });
        jMenu3.add(LaporanBukuMasuk);

        LaporanBukuHilang.setText("Laporan Buku Hilang");
        LaporanBukuHilang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanBukuHilangActionPerformed(evt);
            }
        });
        jMenu3.add(LaporanBukuHilang);

        LaporanPengembalian.setText("Laporan Pengembalian");
        LaporanPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPengembalianActionPerformed(evt);
            }
        });
        jMenu3.add(LaporanPengembalian);

        jMenuBar1.add(jMenu3);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        status.add(Logout);

        jMenuBar1.add(status);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DataAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataAnggotaActionPerformed
       DataAnggota a = new DataAnggota();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_DataAnggotaActionPerformed

    private void LaporanAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanAnggotaActionPerformed
        // TODO add your handling code here:
//        String reportSource = null;
//        String reportDest = null;
//        
//        try{
//            reportSource = System.getProperty("user.dir") + "/src/Laporan/LaporanAnggota.jrxml";
//            reportSource = System.getProperty("user.dir") + "/src/Laporan/LaporanAnggota.jasper";
//            
//            JasperReport jas = JasperCompileManager.compileReport(reportSource);
//            JasperPrint jap = JasperFillManager.fillReport(jas, null , CC);
//            JasperExportManager.exportReportToHtmlFile(jap, reportDest);
//            JasperViewer.viewReport(jap, false);
//        }catch(Exception ex){
//            System.out.println(ex);
//        }
         try{
            String file =  "src/Laporan/LaporanAnggota.jasper";
            JasperPrint jp = JasperFillManager.fillReport(file, null, CC);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LaporanAnggotaActionPerformed

    private void LaporanBukuHilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanBukuHilangActionPerformed
        // TODO add your handling code here:
        try{
            String file =  "src/Laporan/LaporanBukuHilang.jasper";
            JasperPrint jp = JasperFillManager.fillReport(file, null, CC);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LaporanBukuHilangActionPerformed

    private void LaporanBukuMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanBukuMasukActionPerformed
        // TODO add your handling code here:
        try{
            String file =  "src/Laporan/LaporanBukuMasuk.jasper";
            JasperPrint jp = JasperFillManager.fillReport(file, null, CC);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LaporanBukuMasukActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KonfirmasiPeminjam a = new KonfirmasiPeminjam();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         KonfirmasiPengembalian a = new KonfirmasiPengembalian();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        KonfirmasiAnggota a = new KonfirmasiAnggota();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBukuActionPerformed
        DataBuku a = new DataBuku();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_DataBukuActionPerformed

    private void DataPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPeminjamActionPerformed
        DataPeminjam a = new DataPeminjam();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_DataPeminjamActionPerformed

    private void DataDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataDendaActionPerformed
        DataDenda a = new DataDenda();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_DataDendaActionPerformed

    private void DataBukuHilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBukuHilangActionPerformed
       DataBukuHilang a = new DataBukuHilang();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_DataBukuHilangActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         KonfirmasiDenda a = new KonfirmasiDenda();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void LBukuHilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBukuHilangActionPerformed
       KonfirmasiHilang a = new KonfirmasiHilang();
       a.setVisible(true);
       dispose();
                  
    }//GEN-LAST:event_LBukuHilangActionPerformed

    private void LaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPeminjamanActionPerformed
        // TODO add your handling code here:
        try{
            String file =  "src/Laporan/LaporanPeminjaman.jasper";
            JasperPrint jp = JasperFillManager.fillReport(file, null, CC);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LaporanPeminjamanActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void LaporanPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPengembalianActionPerformed
        // TODO add your handling code here:
         try{
            String file =  "src/Laporan/LaporanPengembalian.jasper";
            JasperPrint jp = JasperFillManager.fillReport(file, null, CC);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LaporanPengembalianActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Main a = new Main();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void panelAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelAdminActionPerformed
        // TODO add your handling code here:
        PanelAdmin a = new PanelAdmin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_panelAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petugas_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petugas_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petugas_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petugas_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petugas_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataAnggota;
    private javax.swing.JMenuItem DataBuku;
    private javax.swing.JMenuItem DataBukuHilang;
    private javax.swing.JMenuItem DataDenda;
    private javax.swing.JMenuItem DataPeminjam;
    private javax.swing.JRadioButtonMenuItem LBukuHilang;
    private javax.swing.JMenuItem LaporanAnggota;
    private javax.swing.JMenuItem LaporanBukuHilang;
    private javax.swing.JMenuItem LaporanBukuMasuk;
    private javax.swing.JMenuItem LaporanPeminjaman;
    private javax.swing.JMenuItem LaporanPengembalian;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem panelAdmin;
    private javax.swing.JMenu status;
    // End of variables declaration//GEN-END:variables
}
